# コンテナの構成を記述したファイル
version: "3.0"

services:
  mysql:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Post
      MYSQL_USER: admin
      MYSQL_PASSWORD: "innovator"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 33306:3306

  docker-api:
    container_name: "docker-api"
    # ホストとコンテナのデータを共有する
    volumes:
      - ./app:/app
    build: .
    ports:
      - 8000:8000
